// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAmnxFsdZ8jeTeW2VBvj2jKJkm6m3zDQ',
    appId: '1:70897694595:web:049a86bef11d3ca923e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    authDomain: 'cloneapptiktok-4c440.firebaseapp.com',
    databaseURL: 'https://cloneapptiktok-4c440-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
    measurementId: 'G-WLWXC9TZBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhc3QrmJg9jhM62wP0WFtzrmiDK0iP4X8',
    appId: '1:70897694595:android:a5058e4d999adf1f23e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    databaseURL: 'https://cloneapptiktok-4c440-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbdgSJTOnmCP1aem_0nEmwuRfcwF1Qp8',
    appId: '1:70897694595:ios:1726576a493cb01623e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    databaseURL: 'https://cloneapptiktok-4c440-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
    androidClientId: '70897694595-godqdidp3l221ufjktq2535tcpjifrrq.apps.googleusercontent.com',
    iosClientId: '70897694595-mjmn5c1cka6lkkc5bgmk73f1km9n24kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneAppTiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbdgSJTOnmCP1aem_0nEmwuRfcwF1Qp8',
    appId: '1:70897694595:ios:4485c69c064455b423e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    databaseURL: 'https://cloneapptiktok-4c440-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
    androidClientId: '70897694595-godqdidp3l221ufjktq2535tcpjifrrq.apps.googleusercontent.com',
    iosClientId: '70897694595-7tsjk7rt1jsr9704anr3qevdl89gkloi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneAppTiktok.RunnerTests',
  );
}
